# Site settings
title: sushilthe's blog
email: sushilthe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Another blog, this time by sushilthe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sushilthe.github.io" # the base hostname & protocol for your site
twitter_username: sushilthe
github_username:  sushilthe
# Build settings
markdown: kramdown
exclude: [README.md]
#highlighter: pygments
#permalink: /:title.html